version: '3'

services:
    
    mongo:
        container_name: 
            "api-condominio-mongo"
        image: mongo:latest
        ports: 
            - "27017:27017"
        environment: 
            - MONGO_INITDB_DATABASE="api-condominio"
        restart: always
        volumes: 
            - mongoDBVolumen:/data/db

    app:
        container_name: 
            "api-condominio-app"
        build: .
        restart: always
        ports: 
            - "3000:3000"
        depends_on: 
            - mongo
        environment: 
            - HOST=0.0.0.0
            - PORT=3000
            - MONGOCONNECTION=mongodb://mongo:27017/api-condominio
        volumes: 
            - appVolume:/var/app

volumes:
    mongoDBVolumen:
    appVolume:
