version: '3'

services:
    
    mongo:
        container_name: 
            "api-condominio-mongo"
        image: mongo:latest
        ports: 
            - "27017:27017"
        # networks: 
        #     - apiCondominioNetwork
        environment: 
            - MONGO_INITDB_DATABASE="api-condominio"
        restart: always
        volumes: 
            - /mongoDBVolumen:/data/db

    app:
        container_name: 
            "api-condominio-app"
        build: .
        restart: always
        ports: 
            - "3000:3000"
        # networks: 
        #     - apiCondominioNetwork
        depends_on: 
            - mongo
        environment: 
            # - VIRTUAL_HOST=app
            # - DB_HOST=mongo
            - HOST=0.0.0.0
            - PORT=3000
            - MONGOCONNECTION=mongodb://mongo:27017/api-condominio
        volumes: 
            - .:/var/app

volumes:
    mongoDBVolumen:

networks: 
    apiCondominioNetwork: